sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

language:
  - cpp

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull dcbaker/mesa-ci ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo FROM dcbaker/mesa-ci > Dockerfile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo ADD . /root >> Dockerfile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t withgit . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run withgit /bin/sh -c "cd /root && CC=$CC CXX=$CXX meson build -Dwsi_x11=true -Dwsi_wayland=true -Dvk_intel=true && ninja -C build"; fi
